config/routes.rb
Rails.application.routes.draw do
  root 'twittters#index', as: 'home'
  resources :twittters
  resources :twittters do
    collection do
      post :confirm
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/twittter.rb
class Twittter < ApplicationRecord
    validates :content, presence: true,
                        length: { in: 1..140 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/twittters_controller.rb
class TwitttersController < ApplicationController
  before_action :set_twittter, only: [:show, :edit, :update, :destroy]
  def index
    @twittters = Twittter.all
  end
  
  def new
    @twittter = Twittter.new
  end

  def create
    @twittter = Twittter.new(twittter_params)
    if params[:back]
      render :new
    else
      if @twittter.save
        redirect_to twittters_path, notice: "ツイートしました！"
      else
        render :new
      end
    end
  end

  def confirm
    @twittter = Twittter.new(twittter_params)
    render :new if @twittter.invalid?
  end
  
  def edit
  end

  def update
    if @twittter.update(twittter_params)
      redirect_to home_path, notice: "ツイートを編集しました！"
    else
      render :edit
    end
  end
  
  def destroy
    @twittter.destroy
    redirect_to twittters_path, notice:"ツイートを削除しました！"
  end
  
  
  private
  def twittter_params
    params.require(:twittter).permit(:content)
  end
  
  def set_twittter
    @twittter = Twittter.find(params[:id])
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/twittters_helper.rb
module TwitttersHelper
    def choose_create_or_edit
        if action_name == 'new' || action_name == 'create'
            confirm_twittters_path
        elsif action_name == 'edit'
            twittter_path
        end
    end
end

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <div class="navbar-brand">
        <%= link_to 'Twittter', home_path %>
      </div>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to 'ホームに戻る', home_path %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to 'ツイートする', new_twittter_path %></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TwitterClone</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render '/layouts/nav' %>
    <div class='container'> 
      <%= yield %>
    </div>
  </body>
</html>

app/views/twittters/_form.html.erb
<%= form_with(model: @twittter, local: true, url: choose_create_or_edit ) do |f| %>
    <% if @twittter.errors.any? %>
        <% @twittter.errors.full_messages.each do |msg| %>
            <div class='alert alert-danger'><%= msg %></div>        
        <% end %>       
    <% end %>
    <%= f.label :content,"ツイート内容" %><br>
    <%= f.text_field(:content,{:class => 'form-control'}) %>
  <%= f.submit("ツイートする") %>
  <%= link_to '戻る', :back %>
<% end %>

app/views/twittters/confirm.html.erb
<%= form_with(model: @twittter, url: twittters_path, local: true) do |form| %>
    <h3>以下の内容でツイートする。</h3>
    <%= form.hidden_field :content %>
    <p class="post-content"><%= @twittter.content %></p>
    <%= form.submit  "ツイートする" %>
    <%= link_to '戻る', :back %>
<% end %>

app/views/twittters/edit.html.erb
<%= render 'form' %>

app/views/twittters/index.html.erb
<img src="/panel.jpeg" class="profile-panel">
<div class="row">
    <div class="col-xs-3">
        <div class="panel-footer text-center row">
            <div class="col-sm-2">
                <img src="/avatar.png" height="50px" widht="50px">
            </div>
            <div class="cpl-sm-10">
                <h4>プロフィール</h4>
            </div>
        </div>
    </div>

    <div class="col-xs-6">
    <p><%= notice %></p><br><br>

    <% for @t in @twittters %>
        <div class="panel panel-default post-panel">
            <div class="panel-body row">
                <div class= "col-sm-1">
                    <img src="/avatar.png" height="40px" widht="40px">
                </div>
                <div class= "col-sm-11">
                    <p class="post-content"><%= @t.content %></p>
                </div>
                <div class= "col-sm-11">
                <div class="post-links">                    
                    <%= link_to edit_twittter_path(@t.id) do %>
                        <span class="glyphicon glyphicon-pencil g-links" aria-hidden="true"></span>                
                    <% end %>
                    <%= link_to twittter_path(@t.id), method: :delete ,data: { confirm: '本当に削除してよろしいですか？' } do %>
                        <span class="glyphicon glyphicon-trash g-links" aria-hidden="true"></span> 
                    <% end %>                    
                </div>
                </div>
            </div>
        </div>    
    <% end %>
    </div>

    <div class="col-xs-3">
        <div class="panel panel-defaultel">
            <div class="panel-body">
                <p>＃トレンド</p>
                <p>test1</p>
                <p>test2</p>
                <p>test3</p>
            </div>
        </div>
    </div>
</div>

app/views/twittters/new.html.erb
<%= render 'form' %>